name: spout_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.2
  stacked_services: ^1.4.0
  stacked_generator: ^1.5.1
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  settings_ui: ^2.0.2
  fl_chart: ^0.66.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
