// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHVDfGsYX8sZvpIiZI3zeWfhbcmzmK6Qc',
    appId: '1:262748035438:web:19b3d9081d78fba519097f',
    messagingSenderId: '262748035438',
    projectId: 'spout-app',
    authDomain: 'spout-app.firebaseapp.com',
    storageBucket: 'spout-app.appspot.com',
    measurementId: 'G-F01VEY1NZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyComo6zns2mIyIYWoWHxwF3HhoGqExv1FI',
    appId: '1:262748035438:android:89c4b8d92eb9f0ab19097f',
    messagingSenderId: '262748035438',
    projectId: 'spout-app',
    storageBucket: 'spout-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADeMBH8GhaOQDlgzHPbBh6glh2594-dXE',
    appId: '1:262748035438:ios:484800b0e1baf35919097f',
    messagingSenderId: '262748035438',
    projectId: 'spout-app',
    storageBucket: 'spout-app.appspot.com',
    iosBundleId: 'com.example.spoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADeMBH8GhaOQDlgzHPbBh6glh2594-dXE',
    appId: '1:262748035438:ios:e40fd50eafd04bfc19097f',
    messagingSenderId: '262748035438',
    projectId: 'spout-app',
    storageBucket: 'spout-app.appspot.com',
    iosBundleId: 'com.example.spoutApp.RunnerTests',
  );
}
